# Generated by Django 5.2 on 2025-05-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_common', models.CharField(max_length=200)),
                ('name_official', models.CharField(max_length=200)),
                ('cca2', models.CharField(db_index=True, max_length=2, unique=True)),
                ('capital', models.TextField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', models.JSONField(blank=True, null=True)),
                ('population', models.BigIntegerField(default=0)),
                ('timezones', models.JSONField(blank=True, null=True)),
                ('flags_svg', models.URLField(blank=True, max_length=500, null=True)),
                ('flags_png', models.URLField(blank=True, max_length=500, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name_common'],
            },
        ),
    ]
